add_executable(c_ch25_01_example_linked_list 01_example_linked_list.c)
add_executable(c_ch25_02_example_double_list 02_example_double_list.c)
add_executable(c_ch25_03_example_stack 03_example_stack.c)
add_executable(c_ch25_04_example_queue 04_example_queue.c)
add_executable(c_ch25_05_example_binary_tree 05_example_binary_tree.c)
add_executable(c_ch25_01_deep_dive_ds_patterns 01_deep_dive_ds_patterns.c)
add_executable(c_ch25_02_deep_dive_ds_applications 02_deep_dive_ds_applications.c)
