add_executable(cpp_ch09_01_deep_dive_move_patterns 01_deep_dive_move_patterns.cpp)
add_executable(cpp_ch09_01_example_move_semantics 01_example_move_semantics.cpp)
add_executable(cpp_ch09_02_deep_dive_forwarding_patterns 02_deep_dive_forwarding_patterns.cpp)
add_executable(cpp_ch09_02_example_perfect_forwarding 02_example_perfect_forwarding.cpp)
add_executable(cpp_ch09_03_example_rvalue_reference 03_example_rvalue_reference.cpp)
