add_executable(cpp_ch04_01_deep_dive_virtual_mechanism 01_deep_dive_virtual_mechanism.cpp)
add_executable(cpp_ch04_01_example_inheritance 01_example_inheritance.cpp)
add_executable(cpp_ch04_02_deep_dive_design_patterns 02_deep_dive_design_patterns.cpp)
add_executable(cpp_ch04_02_example_polymorphism 02_example_polymorphism.cpp)
add_executable(cpp_ch04_03_example_multiple_inheritance 03_example_multiple_inheritance.cpp)
