add_executable(c_ch06_01_example_pointer_basics 01_example_pointer_basics.c)
add_executable(c_ch06_02_example_pointer_arithmetic 02_example_pointer_arithmetic.c)
add_executable(c_ch06_03_example_pointer_and_array 03_example_pointer_and_array.c)
add_executable(c_ch06_01_deep_dive_pointer_patterns 01_deep_dive_pointer_patterns.c)
add_executable(c_ch06_02_deep_dive_pointer_pitfalls 02_deep_dive_pointer_pitfalls.c)
