add_executable(cpp_ch36_01_deep_dive_serialization_patterns 01_deep_dive_serialization_patterns.cpp)
add_executable(cpp_ch36_01_example_json_serialize 01_example_json_serialize.cpp)
add_executable(cpp_ch36_02_deep_dive_logging_patterns 02_deep_dive_logging_patterns.cpp)
add_executable(cpp_ch36_02_example_binary_serialize 02_example_binary_serialize.cpp)
add_executable(cpp_ch36_03_example_logging 03_example_logging.cpp)
