add_executable(c_ch02_01_example_arithmetic_operators 01_example_arithmetic_operators.c)
add_executable(c_ch02_02_example_logical_operators 02_example_logical_operators.c)
add_executable(c_ch02_03_example_assignment_operators 03_example_assignment_operators.c)
add_executable(c_ch02_01_deep_dive_operator_precedence 01_deep_dive_operator_precedence.c)
add_executable(c_ch02_02_deep_dive_bitwise_tricks 02_deep_dive_bitwise_tricks.c)
