add_executable(cpp_ch06_01_deep_dive_overload_patterns 01_deep_dive_overload_patterns.cpp)
add_executable(cpp_ch06_01_example_arithmetic_overload 01_example_arithmetic_overload.cpp)
add_executable(cpp_ch06_02_deep_dive_overload_pitfalls 02_deep_dive_overload_pitfalls.cpp)
add_executable(cpp_ch06_02_example_special_operators 02_example_special_operators.cpp)
add_executable(cpp_ch06_03_example_friend 03_example_friend.cpp)
