add_executable(cpp_ch08_01_deep_dive_smart_pointer_patterns 01_deep_dive_smart_pointer_patterns.cpp)
add_executable(cpp_ch08_01_example_unique_ptr 01_example_unique_ptr.cpp)
add_executable(cpp_ch08_02_deep_dive_smart_pointer_pitfalls 02_deep_dive_smart_pointer_pitfalls.cpp)
add_executable(cpp_ch08_02_example_shared_ptr 02_example_shared_ptr.cpp)
