add_executable(c_ch05_01_example_one_dimensional 01_example_one_dimensional.c)
add_executable(c_ch05_02_example_multi_dimensional 02_example_multi_dimensional.c)
add_executable(c_ch05_03_example_array_and_function 03_example_array_and_function.c)
add_executable(c_ch05_01_deep_dive_array_memory 01_deep_dive_array_memory.c)
add_executable(c_ch05_02_deep_dive_array_patterns 02_deep_dive_array_patterns.c)
