find_package(Threads REQUIRED)

add_executable(cpp_ch31_01_deep_dive_atomic_patterns 01_deep_dive_atomic_patterns.cpp)
target_link_libraries(cpp_ch31_01_deep_dive_atomic_patterns Threads::Threads)

add_executable(cpp_ch31_01_example_atomic 01_example_atomic.cpp)
target_link_libraries(cpp_ch31_01_example_atomic Threads::Threads)

add_executable(cpp_ch31_02_deep_dive_async_patterns 02_deep_dive_async_patterns.cpp)
target_link_libraries(cpp_ch31_02_deep_dive_async_patterns Threads::Threads)

add_executable(cpp_ch31_02_example_future_promise 02_example_future_promise.cpp)
target_link_libraries(cpp_ch31_02_example_future_promise Threads::Threads)
