add_executable(cpp_ch24_01_deep_dive_custom_view 01_deep_dive_custom_view.cpp)
add_executable(cpp_ch24_01_example_ranges_basics 01_example_ranges_basics.cpp)
add_executable(cpp_ch24_02_deep_dive_ranges_patterns 02_deep_dive_ranges_patterns.cpp)
add_executable(cpp_ch24_02_example_range_algorithms 02_example_range_algorithms.cpp)
