add_executable(c_ch04_01_example_function_basics 01_example_function_basics.c)
add_executable(c_ch04_02_example_function_advanced 02_example_function_advanced.c)
add_executable(c_ch04_03_example_scope_lifetime 03_example_scope_lifetime.c)
add_executable(c_ch04_01_deep_dive_call_convention 01_deep_dive_call_convention.c)
add_executable(c_ch04_02_deep_dive_recursion_patterns 02_deep_dive_recursion_patterns.c)
