add_executable(cpp_ch07_01_deep_dive_exception_design 01_deep_dive_exception_design.cpp)
add_executable(cpp_ch07_01_example_basic_exception 01_example_basic_exception.cpp)
add_executable(cpp_ch07_02_deep_dive_exception_pitfalls 02_deep_dive_exception_pitfalls.cpp)
add_executable(cpp_ch07_02_example_exception_safety 02_example_exception_safety.cpp)
