add_executable(cpp_ch10_01_deep_dive_template_deduction 01_deep_dive_template_deduction.cpp)
add_executable(cpp_ch10_01_example_function_template 01_example_function_template.cpp)
add_executable(cpp_ch10_02_deep_dive_template_specialization 02_deep_dive_template_specialization.cpp)
add_executable(cpp_ch10_02_example_class_template 02_example_class_template.cpp)
