add_executable(c_ch07_01_example_string_basics 01_example_string_basics.c)
add_executable(c_ch07_02_example_string_operations 02_example_string_operations.c)
add_executable(c_ch07_03_example_string_advanced 03_example_string_advanced.c)
add_executable(c_ch07_01_deep_dive_string_security 01_deep_dive_string_security.c)
add_executable(c_ch07_02_deep_dive_string_patterns 02_deep_dive_string_patterns.c)
