add_executable(cpp_ch12_01_deep_dive_deduction_pitfalls 01_deep_dive_deduction_pitfalls.cpp)
add_executable(cpp_ch12_01_example_auto_deduction 01_example_auto_deduction.cpp)
add_executable(cpp_ch12_02_deep_dive_deduction_patterns 02_deep_dive_deduction_patterns.cpp)
add_executable(cpp_ch12_02_example_decltype 02_example_decltype.cpp)
add_executable(cpp_ch12_03_example_template_deduction 03_example_template_deduction.cpp)
