add_executable(c_ch10_01_example_macro_basics 01_example_macro_basics.c)
add_executable(c_ch10_02_example_macro_advanced 02_example_macro_advanced.c)
add_executable(c_ch10_03_example_predefined_macros 03_example_predefined_macros.c)
add_executable(c_ch10_01_deep_dive_macro_pitfalls 01_deep_dive_macro_pitfalls.c)
add_executable(c_ch10_02_deep_dive_conditional_compile 02_deep_dive_conditional_compile.c)
