find_package(Threads REQUIRED)

add_executable(cpp_ch38_01_deep_dive_lock_free_design 01_deep_dive_lock_free_design.cpp)
target_link_libraries(cpp_ch38_01_deep_dive_lock_free_design Threads::Threads)

add_executable(cpp_ch38_01_example_lock_free_stack 01_example_lock_free_stack.cpp)
target_link_libraries(cpp_ch38_01_example_lock_free_stack Threads::Threads)

add_executable(cpp_ch38_02_deep_dive_lock_free_pitfalls 02_deep_dive_lock_free_pitfalls.cpp)
target_link_libraries(cpp_ch38_02_deep_dive_lock_free_pitfalls Threads::Threads)

add_executable(cpp_ch38_02_example_lock_free_queue 02_example_lock_free_queue.cpp)
target_link_libraries(cpp_ch38_02_example_lock_free_queue Threads::Threads)

add_executable(cpp_ch38_03_example_cas_patterns 03_example_cas_patterns.cpp)
target_link_libraries(cpp_ch38_03_example_cas_patterns Threads::Threads)
