add_executable(cpp_ch35_01_deep_dive_filesystem_patterns 01_deep_dive_filesystem_patterns.cpp)
add_executable(cpp_ch35_01_example_filesystem_basics 01_example_filesystem_basics.cpp)
add_executable(cpp_ch35_02_deep_dive_filesystem_advanced 02_deep_dive_filesystem_advanced.cpp)
add_executable(cpp_ch35_02_example_filesystem_operations 02_example_filesystem_operations.cpp)
