add_executable(c_ch28_01_example_encapsulation 01_example_encapsulation.c)
add_executable(c_ch28_02_example_inheritance 02_example_inheritance.c)
add_executable(c_ch28_03_example_polymorphism 03_example_polymorphism.c)
add_executable(c_ch28_01_deep_dive_oop_patterns 01_deep_dive_oop_patterns.c)
add_executable(c_ch28_02_deep_dive_vtable 02_deep_dive_vtable.c)

if(UNIX)
    target_link_libraries(c_ch28_03_example_polymorphism PRIVATE m)
endif()
