find_package(Threads REQUIRED)

add_executable(cpp_ch34_01_deep_dive_thread_pool_advanced 01_deep_dive_thread_pool_advanced.cpp)
target_link_libraries(cpp_ch34_01_deep_dive_thread_pool_advanced Threads::Threads)

add_executable(cpp_ch34_01_example_thread_pool 01_example_thread_pool.cpp)
target_link_libraries(cpp_ch34_01_example_thread_pool Threads::Threads)

add_executable(cpp_ch34_02_deep_dive_thread_pool_patterns 02_deep_dive_thread_pool_patterns.cpp)
target_link_libraries(cpp_ch34_02_deep_dive_thread_pool_patterns Threads::Threads)
