find_package(Threads REQUIRED)

add_executable(cpp_ch37_01_deep_dive_memory_model 01_deep_dive_memory_model.cpp)
target_link_libraries(cpp_ch37_01_deep_dive_memory_model Threads::Threads)

add_executable(cpp_ch37_01_example_memory_order 01_example_memory_order.cpp)
target_link_libraries(cpp_ch37_01_example_memory_order Threads::Threads)

add_executable(cpp_ch37_02_deep_dive_memory_patterns 02_deep_dive_memory_patterns.cpp)
target_link_libraries(cpp_ch37_02_deep_dive_memory_patterns Threads::Threads)

add_executable(cpp_ch37_02_example_happens_before 02_example_happens_before.cpp)
target_link_libraries(cpp_ch37_02_example_happens_before Threads::Threads)

add_executable(cpp_ch37_03_example_double_checked_locking 03_example_double_checked_locking.cpp)
target_link_libraries(cpp_ch37_03_example_double_checked_locking Threads::Threads)
