add_executable(cpp_ch22_01_deep_dive_concepts_patterns 01_deep_dive_concepts_patterns.cpp)
add_executable(cpp_ch22_01_example_concepts_basics 01_example_concepts_basics.cpp)
add_executable(cpp_ch22_02_deep_dive_concepts_design 02_deep_dive_concepts_design.cpp)
add_executable(cpp_ch22_02_example_custom_concepts 02_example_custom_concepts.cpp)
add_executable(cpp_ch22_03_example_concepts_with_template 03_example_concepts_with_template.cpp)
